[alias]
build-wasm = "build -p verij-plugin --target wasm32-wasip1"
build-wasm-release = "build -p verij-plugin --target wasm32-wasip1 --release"
build-cli = "build -p verij-cli"
build-cli-release = "build -p verij-cli --release"
